/*USER*/
export const SET_USER_LOADING = "SET_USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";
export const SET_LOGIN_SUCCESS = "SET_LOGIN_SUCCESS";

