/*USER*/
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_AUTH_ERROR = "SET_AUTH_ERROR";
export const SET_LOG_OUT_SUCCESS = "SET_LOG_OUT_SUCCESS";
export const SET_LOGIN_SUCCESS = "SET_LOGIN_SUCCESS";

export const SET_BOARDS_SUCCESS = "SET_BOARDS_SUCCESS";
export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS";

export const APP_DARK_MODE = "APP_DARK_MODE";
export const APP_OPEN_MODAL = "APP_OPEN_MODAL";
export const APP_CLOSE_MODAL = "APP_CLOSE_MODAL";
