/*USER*/
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_AUTH_ERROR = "SET_AUTH_ERROR";
export const SET_LOG_OUT_SUCCESS = "SET_LOG_OUT_SUCCESS";
export const SET_LOGIN_SUCCESS = "SET_LOGIN_SUCCESS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SET_BOARDS_SUCCESS = "SET_BOARDS_SUCCESS";
export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS";
export const DELETE_BOARD_SUCCES = "DELETE_BOARD_SUCCES";
export const GET_BOARD_BY_ID_SUCCESS = "GET_BOARD_BY_ID_SUCCESS";
export const GET_BOARD_BY_ID_ERROR = "GET_BOARD_BY_ID_ERROR";

export const APP_DARK_MODE = "APP_DARK_MODE";
export const APP_OPEN_MODAL = "APP_OPEN_MODAL";
export const APP_CLOSE_MODAL = "APP_CLOSE_MODAL";
